### ISSUE TITLE
Type mismatch when passing default values

### ISSUE THREAD

**Issue by connorshea** [AaronC81/parlour#1]
I have `test.rb`:

```ruby
require_relative './lib/parlour'

generator = Parlour::RbiGenerator.new
generator.root.create_module('A') do |a|
  a.create_class('Foo') do |foo|
    foo.create_method('add_two_integers', [
      Parlour::RbiGenerator::Parameter.new('a', type: 'Integer', default: '10'),
      Parlour::RbiGenerator::Parameter.new('b', type: 'String', default: '10')
    ], 'String')
  end
end

puts generator.rbi # => Our RBI as a string
```

and it outputs this:

```ruby
module A
  class Foo
    sig { params(a: Integer, b: String).returns(String) }
    def add_two_integers(a = 10, b = 10); end
  end
end
```

`Parlour::RbiGenerator::Parameter.new('a', type: 'Integer', default: '10')` and `Parlour::RbiGenerator::Parameter.new('b', type: 'String', default: '10')` both generate an `Integer` as the default value, when `b` should have `10` represented as a `String`.

The library shouldn't allow a default that doesn't match the type of the parameter (also, allow non-string defaults, currently passing an Integer as the default causes an error).

**Comment by connorshea** [comment]
The biggest problem with this is that it makes it impossible to pass `nil` as a default parameter since there's no way (AFAIK) to distinguish between default not being defined and default being explicitly defined as `nil` :/

**Comment by AaronC81** [comment]
The `nil` issue was also a problem with Sord, and I'm not too sure how to approach it...

**Comment by connorshea** [comment]
Have a special case where `'nil'` is turned into `nil`? :P

**Comment by AaronC81** [comment]
The main challenge with interpreting values while generating defaults is not just representing `nil`, but also all manner of other possible default values. For example, how would this method be represented?

```ruby
def foo(x = SomeClass.new); end
```

I went with verbatim strings everywhere for defaults when writing Parlour, as it meant I didn't have to solve this problem. (For example, if you wanted a string default value, you'd use `default: '\'A string\''`, or for the above example you'd just use `default: 'SomeClass.new'`.) It's certainly not elegant and there's probably a better solution, but it's versatile for now.

**Comment by connorshea** [comment]
Would `"'default'"` also work?

**Comment by AaronC81** [comment]
For strings, yeah, that should work!

**Comment by connorshea** [comment]
I think this just needs to have some better documentation and we can close this issue, nothing needs to be changed.

**Comment by AaronC81** [comment]
Good documentation is sorely needed; I'll work on that today :)
Sorry for any confusion!

**Comment by connorshea** [comment]
The docs are much better now, though they’re not available anywhere right now. Maybe use the same solution discordrb uses for deploying the YARD docs to GitHub Pages, or look at a GitHub Action for it?

RubyDoc.info is pretty unstable lately so I’d rather not rely on it.

**Comment by connorshea** [comment]
Anyway, we should open a new issue for hosting the docs. I’ll close this.
