### ISSUE TITLE
Support sealed! calls in rbi generation

### ISSUE THREAD

**Issue by timgaleckas** [AaronC81/parlour#106]
I have a module with `sealed!` in the definition. https://sorbet.org/docs/sealed#docsNav

When I use `bundle exec parlour` to generate the rbi file, it's not output in the rbi.

**Comment by AaronC81** [comment]
@timgaleckas Thanks for opening an issue, this is a good thing to have available in Parlour!

I've opened #107 which adds parsing and generation of `sealed!`, so if that does everything you need then I can get it merged :+1:

**Comment by timgaleckas** [comment]
I commented on the PR. Looks good. Thanks.

**Comment by AaronC81** [comment]
Great!
