### ISSUE TITLE
Type signatures not correctly combined

### ISSUE THREAD

**Issue by camertron** [AaronC81/parlour#125]
**Describe the bug**
Hey Parlour team! I'm using Parlour to combine the type definitions in sorbet/rbi for my [kube-dsl](https://github.com/getkuby/kube-dsl) gem. I have a bunch of Ruby files in lib/kube-dsl and a bunch of corresponding .rbi files in sorbet/rbi/kube-dsl. My understanding is that I should be able to add Parlour to my bundle and run `bundle exec parlour` to get a single rbi/kube-dsl.rbi file that contains all the type information for the whole gem. Unfortunately after doing so, the type information in rbi/kube-dsl.rbi is very incomplete, i.e. missing 90% of the sigs present in sorbet/rbi/kube-dsl. I've tried creating a .parlour file and including various options/paths, but all to no avail.

**To Reproduce**
Clone kube-dsl and run `bundle exec parlour` (there is no .parlour file).

**Expected behavior**
I expect the type information present in all the .rbi files in the sorbet/rbi/kube-dsl directory tree to be present in rbi/kube-dsl.rbi.

**Actual behavior**
Parlour runs without any console output. rbi/kube-dsl.rbi is missing almost all the type signatures present in sorbet/rbi/kube-dsl, and the ones it has managed to find are all `T.untyped`. Here's an example:

```ruby
class MutatingWebhook < ::KubeDSL::DSLObject
  sig { returns(T.untyped) }
  def serialize; end

  sig { returns(T.untyped) }
  def kind_sym; end
end
```

In the example above, both `serialize` and `kind_sym` should have complete type signatures, and there should be many more methods. It looks as if Parlour isn't "seeing" all the .rbi files in sorbet/rbi/kube-dsl.

**Additional information**
No plugins. Parlour version is 6.0.1.

Thanks!

**Comment by AaronC81** [comment]
Hey - thank you for giving such a comprehensive problem description, I was able to track this down pretty fast thanks to that!

Parlour has some defaults for what files it parses - I don't believe these are documented anywhere sorry, but they probably ought to be. These defaults are:

- The `lib` directory is checked for signatures, and
- The `sorbet` and `spec` directories are always ignored

This means the defaults aren't suitable for your purposes - the `lib` folder doesn't contain any useful signatures for kube-dsl, and all of your signatures are in fact in `sorbet` which is being excluded.

To override these defaults, we can [specify some .parlour keys](https://github.com/AaronC81/parlour/wiki/The-.parlour-file#parser):

```yaml
parser:
    # Don't exclude the `sorbet` directory, overriding the default
    excluded_paths: []

    # Look only in the kube-dsl types directory
    included_paths:
        - ./sorbet/rbi/kube-dsl
```

Please try the above .parlour file and see if you get better results. It looks more like what you're expecting as far as I can tell!

```ruby
module V1
  class MutatingWebhook < ::KubeDSL::DSLObject
    sig { returns(T::Hash[Symbol, T.any(String, Integer, Float, T::Boolean, T::Array[T.untyped], T::Hash[Symbol, T.untyped])]) }
    def serialize; end

    sig { returns(Symbol) }
    def kind_sym; end

    # And many more methods...
  end
end
```

**Comment by camertron** [comment]
Awesome, thanks for the super fast response @AaronC81 :) That .parlour file did the trick!
