### ISSUE TITLE
Allow arbitrary input to be added to a class/module

### ISSUE THREAD

**Issue by connorshea** [AaronC81/parlour#13]
**Is your feature request related to a problem? Please describe.**
sorbet-rails generates some code like this:

```ruby
class GameEngine < ApplicationRecord
  extend T::Sig
  extend T::Generic
  extend GameEngine::ModelRelationShared
  include GameEngine::InstanceMethods
  Elem = type_template(fixed: GameEngine)
end
```

This currently cannot be reproduced via Parlour, as far as I know.

**Describe the solution you'd like**
I'd like a method like `add_code` or `add_arbitrary` that'd take a String or HEREDOC (which I think is also just a string?) that would allow me to inject any arbitrary code into a class.

```ruby
generator = Parlour::RbiGenerator.new
generator.root.create_class('GameEngine', superclass: 'ApplicationRecord') do |game_engine|
  add_extend('T::Sig')
  add_extend('T::Generic')
  add_extend('GameEngine::ModelRelationShared')
  add_include('GameEngine::InstanceMethods')
  add_arbitrary('Elem = type_template(fixed: GameEngine)')
end

generator.rbi
  # =>
  # class GameEngine < ApplicationRecord
  #   extend T::Sig
  #   extend T::Generic
  #   extend GameEngine::ModelRelationShared
  #   include GameEngine::InstanceMethods
  #   Elem = type_template(fixed: GameEngine)
  # end
```

**Describe alternatives you've considered**
I think it'd be useful to have an 'escape hatch' instead of needing to implement a generator for every possible piece of code in Parlour.

**Comment by AaronC81** [comment]
This is a good plan for anything that we haven't thought of!

It will be possible to generate this particular code entirely through Parlour's normal methods when #10 is implemented, however. I'll get on it!
