### ISSUE TITLE
Error generating RBI file for a T::Enum with a single value

### ISSUE THREAD

**Issue by robertjlooby** [AaronC81/parlour#132]
**Describe the bug**
The RBI generated for a T::Enum with a single value is invalid.

**To Reproduce**
With a minimal project like:

```ruby
# Gemfile
gem 'parlour'
gem 'sorbet'

# lib/test.rb
class Test < T::Enum
  enums do
    Value = new('value')
  end
end
```

Run:
- `bundle`
- `bundle exec srb init`
- `bundle exec parlour`

**Expected behavior**
I'd expect the generated RBI to be

```ruby
class Test < T::Enum
  enums do
    Value = new('value')
  end
end
```

**Actual behavior**
The RBI generated at `rbi/test.rbi` is

```ruby
# typed: strong
class Test < T::Enum
  enums do
     = new
     = new
    new = new
  end

end
```

Adding a second value to the `enums` block makes parlour generate the expected RBI.

**Additional information**
- parlour 8.0.0
- sorbet 0.5.6435

**Comment by AaronC81** [comment]
Good catch, should be sorted by #133! 

The fact that Ruby's AST condenses a body with one expression into just that expression always trips me up, and that was what was happening here.
