### ISSUE TITLE
Make the first parameter of various method "name" without using keyword argument

### ISSUE THREAD

**Issue by manhhung741** [AaronC81/parlour#28]
**Is your feature request related to a problem? Please describe.**
This is a personal taste, but I feel the `name:` argument is overly verbose. 

Consider:
```
root.create_module("FooModule")
vs
root.create_module(name: "FooModule")
```
The first option is just as clear. It's also more readable. I've forgotten the `name:` args a handful of time now. I'm sure I'll get used to it but it'd be nice to support the first syntax.

**Describe the solution you'd like**
Make `name` a normal argument instead of keyword arg.

**Describe alternatives you've considered**
If you don't want to drop `name:`, we can keep supporting `name:` and a first argument that'll be used as name
eg:
```
def create_module(dname=nil, name:)
  name = name || dname
end
```
But the first option is cleaner in the long term. There is only a  few current users who need to codemod once.

**Additional context**
Add any other context about the feature request here.

**Comment by AaronC81** [comment]
This certainly makes sense, and will also be consistent because every single RbiObject has a name by definition (except `Arbitrary` I think). I'll look into implementing this and updating docs!
