### ISSUE TITLE
Add a way to generate a "type_parameter" for a method

### ISSUE THREAD

**Issue by manhhung741** [AaronC81/parlour#41]
**Describe the bug**
Add a way to generate a "Type_parameter" for a method. It's a feature supported by sorbet generic method

https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20Box%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%20%20Elem%20%3D%20type_member%0A%0A%20%20sig%20%7Bparams(x%3A%20Elem).void%7D%0A%20%20def%20initialize(x)%0A%20%20%20%20%40x%3Dx%0A%20%20end%0A%0A%20%20sig%20do%0A%20%20%20%20type_parameters(%3AU)%0A%20%20%20%20.params(%0A%20%20%20%20%20%20blk%3A%20T.proc.params(arg0%3A%20Elem).returns(T.type_parameter(%3AU))%2C%0A%20%20%20%20)%0A%20%20%20%20.returns(Box%5BT.type_parameter(%3AU)%5D)%0A%20%20end%0A%20%20def%20map(%26blk)%0A%20%20%20%20Box.new(blk.call(%40x))%0A%20%20end%0Aend%0A%0ABox%5BInteger%5D.new(0).map(%26%3Asucc).map(%26%3Afoo)

**Comment by manhhung741** [comment]
I'm trying to generate something like this but IDK how
https://github.com/sorbet/sorbet/blob/master/rbi/core/enumerable.rbi#L512

Btw, I think there should be an escape hatch to generate a random sig just in case there are new features released in Sorbet that Parlour hasn't added yet.

**Comment by connorshea** [comment]
You can add arbitrary code, if that’s what you’re asking for with an escape hatch.

**Comment by manhhung741** [comment]
How to add arbitrary code?

**Comment by connorshea** [comment]
https://aaronc81.github.io/parlour/Parlour/RbiGenerator/Namespace.html#create_arbitrary-instance_method

**Comment by AaronC81** [comment]
I have a PR which implements type parameters here: https://github.com/AaronC81/parlour/pull/47

I'm not too familiar with Sorbet's type parameters, so it would be great if you could check that this does everything you need it to do.
