### ISSUE TITLE
Error 5028 for "Regex = Regex = T.let(T.unsafe(nil), Regexp)"

### ISSUE THREAD

**Issue by jasnow** [AaronC81/parlour#48]
**To Reproduce**

When I ran parlour's "rake tc" command this morning, I got:
```
sorbet/rbi/sorbet-typed/lib/ruby/all/resolv.rbi:526:
Constants must have type annotations with T.let when specifying # typed: strict https://srb.help/5028
    526 |      Regex = Regex = T.let(T.unsafe(nil), Regexp)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

This is related to the 8/19/2019 3:16pm "discuss" post.

**Comment by jasnow** [comment]
Related PR (maybe): https://github.com/sorbet/sorbet-typed/pull/115

**Comment by jasnow** [comment]
When I went over to the "resolv.rbi" file mentioned above, I see that it is autogenerated so I did not want to edit it.  Suggest adding how you refresh this file in the README/documentation. Thanks.

**Comment by AaronC81** [comment]
Good suggestion - I've added this to the README. Thanks!
