### ISSUE TITLE
Sort the methods by name before exporting

### ISSUE THREAD

**Issue by manhhung741** [AaronC81/parlour#59]
**Is your feature request related to a problem? Please describe.**
Currently, I think the method signatures are outputted in the order they are created. In certain cases, I find it useful to be able to sort the methods in the same module/object before printing them out. It'll b

**Describe the solution you'd like**
An option to sort methods/child modules before calling `parlour.rbi`. Or calling `parlour.rbi(sort_options:...)`

**Describe alternatives you've considered**
None

**Additional context**
I'm using Parlour to generate rbis for routes generated by rails. Rails' API may call it in any order. When there is a new route added, the whole file might be changed. If there is an option to sort the generated methods, it'll give a more consistent output.

https://github.com/chanzuckerberg/sorbet-rails/blob/master/lib/sorbet-rails/routes_rbi_formatter.rb#L51

**Comment by AaronC81** [comment]
This would be a great feature to have; I'll probably add it to the `Options` class which is given to `RbiGenerator`. I'll look into implementing this shortly!

**Comment by AaronC81** [comment]
@manhhung741 I think I've implemented what you need - if you're happy with #60 I can merge it!

**Comment by manhhung741** [comment]
Commented! It looks great. Thank you for such a quick turn around!

**Comment by AaronC81** [comment]
Great!
