### ISSUE TITLE
Option to skip including parentheses when there aren't parameters

### ISSUE THREAD

**Issue by connorshea** [AaronC81/parlour#6]
Normally parlour will output a method like this:

```ruby
sig { void }
def parameterless(); end
```

But I'd like to output this instead:

```ruby
sig { void }
def parameterless; end
```

Ruby also technically supports this, but it's blasphemy so we shouldn't support it:

```ruby
def bad param, param2, param3
  puts 'why would you do this to me'
end
```

**Comment by AaronC81** [comment]
Yeah, this would be a good default, and shouldn't be too hard to implement!
