### ISSUE TITLE
Specify version of sorbet-runtime in gemspec file

### ISSUE THREAD

**Issue by manhhung741** [AaronC81/parlour#61]
**Describe the bug**
Can we specify the version of sorbet in the gemspec file? Without the specification, every time I release a new version of `sorbet-rails`, it seems to try to install the newest version of sorbet & sorbet-runtime. This is not desirable because the codebases that use `sorbet-rails` might be using an old version of sorbet and don't want to upgrade yet.

I think the cause is this:
```
  spec.add_dependency "sorbet-runtime"
```

**To Reproduce**
Upgrade `sorbet-rails` in a repo that use a fixed version of `sorbet-runtime`. Observe that it also tries to upgrade sorbet-runtime's version of the repo.

**Expected behavior**
It shouldn't try to change the sorbet-runtime version of the repo

**Actual behavior**

**Additional information**

**Comment by manhhung741** [comment]
It is also recommended by RubyGems specifications to include specific version of the dependent gem
https://guides.rubygems.org/patterns/#declaring-dependencies

**Comment by AaronC81** [comment]
Thank you - this is a good suggestion! I'll look at fixing the version soon.

**Comment by AaronC81** [comment]
@manhhung741 - To solve this issue, which of these would be best?

  - Fix a particular version of sorbet-runtime (e.g. `== 0.5.5188`)
  - Specify a minor-version constraint for sorbet-runtime (e.g. `~> 0.5`)
  - Something else?

I'm relatively inexperienced with dependency management, I'm afraid.

**Comment by manhhung741** [comment]
Thank you for looking!

I don’t have a lot of experience either, but I think it’s preferred to
specify a particular version. I noticed that if you put a specific version
for sorbet, Rubygems will use that specific version for parlour without
overriding the gem version globally. You’re free to use any version in that
case.

We likely don’t want a minor version constraint like ~ 0.5 because sorbet
can change a lot within a minor version (they constantly release new
versions with every commits)

**Comment by AaronC81** [comment]
Apologies for the huge delay on me looking into this

Does this `fix-sorbet-runtime-version` branch fix this issue? If so, I'll release a new version once this is closed so you can start using that version in sorbet-rails.

**Comment by connorshea** [comment]
Wouldn't this just cause the version of sorbet used by any projects with parlour as a dependency to be locked until parlour is updated? That doesn't seem like a good idea to me.

**Comment by AaronC81** [comment]
If that were the case, it indeed wouldn't be a great idea. @manhhung741 said:

>  I noticed that if you put a specific version for sorbet, Rubygems will use that specific version for parlour without overriding the gem version globally.

Though I haven't tested this myself.

**Comment by AaronC81** [comment]
It looks like @connorshea's suggestion might be correct. I created three example gems to test this, and it looks like Bundler complains if you pin versions within dependencies.

I created:

  - A gem `A` with three versions, 1.0.0 - 3.0.0.
  - A gem `B` which depends on specifically version 2.0.0 of `A`.
  - A gem `C` which depends on `B` and specifically version 3.0.0 of `A`.

Bundler isn't able to resolve `C`'s dependencies:

```
Bundler could not find compatible versions for gem "A":
  In Gemfile:
    C was resolved to 1.0.0, which depends on
      B (= 1.0.0) was resolved to 1.0.0, which depends on
        A (= 2.0.0)

    C was resolved to 1.0.0, which depends on
      A (= 3.0.0)
```

I think this models the situation here accurately enough, where `A` = sorbet-runtime, `B` = parlour and `C` = sorbet-rails. So, unless I'm missing something, it might not be possible to pin the version like this.

**Comment by manhhung741** [comment]
That's interesting. Thanks for digging into it. I saw that in the branch, you pinned `sorbet-runtime` version to `=0.5.x`. That may be why it cannot resolve the version of sorbet. I think my problem is with having no version of `sorbet-runtime` at all. How about we use `>=`, or `~>0.5` like the way you specify dependency of other gems?

**Comment by AaronC81** [comment]
I've relaxed the restriction to `~> 0.5` - please could you check if this resolves your issues in sorbet-rails?

**Comment by manhhung741** [comment]
Thank you. That sounds good to me. I also realize we should pin the sorbet version in our codebase's Gemfile so that it's not affected by the gems.

**Comment by manhhung741** [comment]
An alternative that's more flexible is
```
sorbet-runtime, ">= 0.5"
```

**Comment by AaronC81** [comment]
I'll merge with `>= 0.5` and prepare a new release of Parlour. Thank you for your help testing things!

**Comment by manhhung741** [comment]
Thank you!
