### ISSUE TITLE
Loosen dependencies on commander and rainbow

### ISSUE THREAD

**Issue by connorshea** [AaronC81/parlour#62]
```
parlour (1.0.0)
   commander (~> 4.4.0)
   rainbow (~> 3.0.0)
```

I think it's pretty unlikely that either commander or rainbow will have significant breakage between minor versions, so limiting seems unnecessary. Could we update the gemspec to rely on `~> 4.5` and `~> 3.0` respectively?

**Comment by AaronC81** [comment]
Good spot, thanks!
