### ISSUE TITLE
Parser fails on undeclared block argument

### ISSUE THREAD

**Issue by kirbycool** [AaronC81/parlour#65]
Version: 2.0.0

Hi! First of all, thanks for the great project!

I ran into an interesting crash when running parlour on my codebase. When parsing, parlour crashes with `Parlour::ParseError: mismatching number of arguments in sig and def` if a function has a block argument in the def but not in the sig (I had some of these generated by rails_rbi).
https://github.com/AaronC81/parlour/blob/master/lib/parlour/type_parser.rb#L392

Example:
```ruby
# typed: strong

class A
  extend T::Sig

  sig { params(a: String).void }
  def bar(a, &blk); end
end
```
```
> Parlour::TypeLoader.load_file('./test.rb')
Parlour::ParseError: mismatching number of arguments in sig and def
```

Suprisingly, this seems like valid sorbet, even though it's not mentioned in the doc.
https://sorbet.run/#%23%20typed%3A%20strong%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20params(a%3A%20String).void%20%7D%0A%20%20def%20bar(a%2C%20%26blk)%3B%20end%0Aend%0A

**Comment by AaronC81** [comment]
Well spotted! This should definitely be parsed correctly.

I _believe_ Sorbet implicitly adds `&blk` internally onto the end of signatures which don't specify a block argument. If I remember correctly I've seen this happen in the Sorbet LSP extension for VS Code. That's probably why Sorbet accepts this.

**Comment by kirbycool** [comment]
Got it, that makes sense. How do you think we should fix this? Add some edge case logic to append an arg to `sig_args` if there's a `:blockarg` `def_param` with no corresponding `sig_arg`?
I can find some time to work on this if you're busy.

**Comment by AaronC81** [comment]
That would work! Another option is that the `&blk` could simply be dropped when parsing, as the meaning would remain the same, and it would also keep the sig the same (which seems good since dealing with sigs is the main goal of Parlour).

I'd gladly accept a PR for this if you're willing to write one; thanks! Don't worry if you're not able to, I'd be able to find time to do it within the next fortnight.
