### ISSUE TITLE
TypeLoader.load_project crashes on empty ruby source file

### ISSUE THREAD

**Issue by bradleybuda** [AaronC81/parlour#71]
**Describe the bug**
I have a file in my source tree whose complete contents is:
```ruby
# typed: strong
```
No, there's no good reason for this - now that I've discovered this file I've deleted it, but it is valid Ruby and sorbet has no problem with it.

When I run `Parlour::TypeLoader.load_project('my/project/dir')`, it fails with this error:

```
TypeError (Parameter 'ast': Expected type Parser::AST::Node, got type NilClass)
Caller: /Users/brad/src/parlour/lib/parlour/type_parser.rb:111
Definition: /Users/brad/src/parlour/lib/parlour/type_parser.rb:95
```

**To Reproduce**
This one-liner reproduces the issue for me:
```ruby
Parlour::TypeLoader.load_source('# typed: strong')
```

**Expected behavior**
I assume this file would be ignored in the AST and processing would continue on the rest of the project without this file contributing anything? I'm brand new to Parlour, this might not be the correct expected behavior.

**Actual behavior**
Crash as described above

**Additional information**
If a maintainer can advise on the correct expected behavior, I might be able to put together a pull request to fix this. Thanks!

**Comment by bradleybuda** [comment]
One slightly-more realistic way this bug can manifest itself is in a default Rails application. A `rails new` app contains a number of `.rb` files that are full-commented-out, for example, `config/initializers/mime_types.rb` was generated to look like this in my Rails 5.2 app (there are other examples):

```ruby
# Be sure to restart your server when you modify this file.

# Add new mime types for use in respond_to blocks:
# Mime::Type.register "text/richtext", :rtf
```

`sorbet rbi suggest-typed` will modify this file to start with `# typed: strong` but leave it fully-commented out, and a file with just comments will also trigger this bug.

**Comment by AaronC81** [comment]
Good find! This was a pretty easy fix I think - would you mind trying the master branch on your repo to see if this is resolved?

**Comment by bradleybuda** [comment]
Fixed! Thank you for the super-quick response!
