### ISSUE TITLE
TypeLoader#load_project failing when method has the same name as attr_*

### ISSUE THREAD

**Issue by jeffcarbs** [AaronC81/parlour#79]
**Describe the bug**
`Parlour::TypeLoader.load_project` fails when a class defines a method with the same name as an attr_*.

**To Reproduce**
```ruby
namespace = Parlour::TypeLoader.load_source(<<-RUBY)
  class A
    attr_writer :foo
    def foo; end
  end
RUBY

# Called within `load_project`
Parlour::ConflictResolver.new.resolve_conflicts(namespace) do |n, o|
  raise "conflict of #{o.length} objects: #{n}"
end
```

**Expected behavior**
No conflict.

**Actual behavior**
Conflict.

**Additional information**
In the example provided it's an `attr_writer` mixed with a "getter" method which actually don't conflict in real life. Interestingly, `attr_writer` mixed with a "setter" method does not raise an exception since the ConflictResolver is only matching on names but one would override the other in real life.

i.e. this has no conflicts:
```
namespace = Parlour::TypeLoader.load_source(<<-RUBY)
  class A
    attr_writer :foo
    def foo=(v); end
  end
RUBY
```

**Comment by AaronC81** [comment]
Good catch! I'll look into fixing this soon.

**Comment by AaronC81** [comment]
@jeffcarbs The `fix-79` branch should hopefully fix this. Would appreciate if you could give it a quick run on your codebase to verify - thanks!

**Comment by jeffcarbs** [comment]
@AaronC81 - This was resolved on the `fix-79` branch 👍
