### ISSUE TITLE
constants on a metaclass?

### ISSUE THREAD

**Issue by will** [AaronC81/parlour#90]
I have a gem that provides something like

``` ruby
class Base
  extend Enumerable
end
```

and I'm trying out parlour to generate RBI for subclasses of that. Sorbet gets really angry about not having `Elem = type_member(somethingsomething)` (even though that seems completely undocumented).

I had been fixing that by removing the `extend` in the gems rbi since I'm not actually using any of those methods, however I just discovered that I can also fix it by doing

``` ruby
class MyThing < Base
  class << self
    Elem = type_member(fixed: MyThing)
  end
end
```

I can't find a way to generate this from parlour though. Is it possible?

**Comment by AaronC81** [comment]
This isn't possible right now, I seem to have overlooked this. I'm surprised this hasn't been run into sooner! I'll look into adding it.

If you need a quick and dirty fix before I get round to adding this and pushing out a version with it, you should be able to use [`Namespace#create_arbitrary`](https://aaronc81.github.io/parlour/Parlour/RbiGenerator/Namespace.html#create_arbitrary-instance_method):

```ruby
x.create_arbitrary("class << self")
x.create_constant(...)
x.create_arbitrary("end")
```

**Comment by will** [comment]
Oh thanks for pointing out `create_arbitrary`, I missed that when searching through the doc site, that is handy :)

**Comment by will** [comment]
Thank you!
